# -*- coding: utf-8 -*-

INSULTS = (
    "A most notable coward, an infinite and endless liar, an hourly promise breaker, the owner of no one good quality.",
    "Away, you starvelling, you elf-skin, you dried neat’s-tongue, bull’s-pizzle, you stock-fish!",
    "Away, you three-inch fool! ",
    "Come, come, you froward and unable worms!",
    "I am sick when I do look on thee ",
    "I do desire that we may be better strangers.",
    "I’ll beat thee, but I would infect my hands.",
    "I scorn you, scurvy companion. ",
    "More of your conversation would infect my brain.",
    "Out of my sight! Thou dost infect my eyes.",
    "Poisonous bunch-backed toad! ",
    "Tempt not too much the hatred of my spirit, for I am sick when I do look on thee.",
    "There’s small choice in rotten apples.",
    "Thine face is not worth sunburning.",
    "Thou art as fat as butter.",
    "Thou art unfit for any place but hell.",
    "Thou hast no more brain than I have in mine elbows",
    "Thou lump of foul deformity",
    "You poor, base, rascally, cheating lack-linen mate! ",
    "You are as a candle, the better burnt out.",
    "Your abilities are too infant-like for doing much alone.",
    "Villain, I have done thy mother.",
    "You, minion, are too saucy.",
)
