# -*- coding: utf-8 -*-

KAOMOJIS = {
    'ak47': "¯¯̿̿¯̿̿'̿̿̿̿'̿̿'̿̿̿̿'̿̿̿)͇̿̿)̿̿̿̿ '̿̿̿̿\̵͇̿̿\=(•̪̀●́)=o/̵͇̿̿/'̿̿ ̿ ̿̿'",
    'begging_cat': "八(＾□＾*)",
    'bow': "ｍ（｡≧ _ ≦｡）ｍ",
    'bouba': 'ˁ(⦿ᴥ⦿)ˀ',
    'bromance': "(っ˘з(˘⌣˘ )",
    'crow': ". . . ()°<",
    'cry': "(ᵕ̣̣̣﹏ᵕ̣̣̣)",
    'dancer': 'ᕕ( ᐛ )ᕗ',
    'doge_thug': " (*゜▽゜)*。_。)*゜▽゜)*。_。)",
    'el-famoso': "(ง ื▿ ื)ว",
    'expressionless': "(--_--)",
    'facepalm': '(◞‸ლ)',
    'feels_good': "∩(︶▽︶)∩",
    'kissing': '(╯3╰)',
    'if_u_know_what_i_mean': '(¬‿¬)',
    'magic_wand': "╰( ⁰ ਊ ⁰ )━☆ﾟ.*･｡ﾟ",
    'me_gusta': '(👁 ͜ʖ👁)',
    'not_sure': "눈_눈",
    'octopus': 'Ｃ:。ミ',
    'over_9000': "┻━┻ ︵ヽ(`□´)ﾉ︵ ┻━┻",
    'pls': "_(:3」∠)_",
    'pray': "八(＾□＾*)",
    'ru_fkidding_me': "(¬_¬)",
    'scream': 'ヽ(ﾟДﾟ)ﾉ',
    'shrug': '¯\_(⊙︿⊙)_/¯',
    'shushing_face': "( ﾟ∀(・－・)",
    'so_cute': "c〳 ݓ ﹏ ݓ 〵੭",
    'success-kid': "(•̀ᴗ•́)و ̑̑'",
    'sweat': "(一。一;;）",
    'take_my_money': '(╯°□°）╯$ $ $',
    'thinking_black_guy': 'Σ (°ζ‿°　)',
    'this_is_fine': 'V●ᴥ●V',
    'thumbsup': "(*＾▽＾)b",
    'tired_face': "(ᗒᗣᗕ)՞",
    'wave': "~ヾ(＾∇＾)",
    'wtf': "ᕙ(⇀‸↼‶)ᕗ'",
}
